// Code generated by go-swagger; DO NOT EDIT.

package auditlog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/goharbor/harbor/src/server/v2.0/models"
)

// ListAuditLogEventTypesOKCode is the HTTP code returned for type ListAuditLogEventTypesOK
const ListAuditLogEventTypesOKCode int = 200

/*
ListAuditLogEventTypesOK Success

swagger:response listAuditLogEventTypesOK
*/
type ListAuditLogEventTypesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.AuditLogEventType `json:"body,omitempty"`
}

// NewListAuditLogEventTypesOK creates ListAuditLogEventTypesOK with default headers values
func NewListAuditLogEventTypesOK() *ListAuditLogEventTypesOK {

	return &ListAuditLogEventTypesOK{}
}

// WithPayload adds the payload to the list audit log event types o k response
func (o *ListAuditLogEventTypesOK) WithPayload(payload []*models.AuditLogEventType) *ListAuditLogEventTypesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list audit log event types o k response
func (o *ListAuditLogEventTypesOK) SetPayload(payload []*models.AuditLogEventType) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAuditLogEventTypesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.AuditLogEventType, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListAuditLogEventTypesUnauthorizedCode is the HTTP code returned for type ListAuditLogEventTypesUnauthorized
const ListAuditLogEventTypesUnauthorizedCode int = 401

/*
ListAuditLogEventTypesUnauthorized Unauthorized

swagger:response listAuditLogEventTypesUnauthorized
*/
type ListAuditLogEventTypesUnauthorized struct {
	/*The ID of the corresponding request for the response

	 */
	XRequestID string `json:"X-Request-Id"`

	/*
	  In: Body
	*/
	Payload *models.Errors `json:"body,omitempty"`
}

// NewListAuditLogEventTypesUnauthorized creates ListAuditLogEventTypesUnauthorized with default headers values
func NewListAuditLogEventTypesUnauthorized() *ListAuditLogEventTypesUnauthorized {

	return &ListAuditLogEventTypesUnauthorized{}
}

// WithXRequestID adds the xRequestId to the list audit log event types unauthorized response
func (o *ListAuditLogEventTypesUnauthorized) WithXRequestID(xRequestID string) *ListAuditLogEventTypesUnauthorized {
	o.XRequestID = xRequestID
	return o
}

// SetXRequestID sets the xRequestId to the list audit log event types unauthorized response
func (o *ListAuditLogEventTypesUnauthorized) SetXRequestID(xRequestID string) {
	o.XRequestID = xRequestID
}

// WithPayload adds the payload to the list audit log event types unauthorized response
func (o *ListAuditLogEventTypesUnauthorized) WithPayload(payload *models.Errors) *ListAuditLogEventTypesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list audit log event types unauthorized response
func (o *ListAuditLogEventTypesUnauthorized) SetPayload(payload *models.Errors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAuditLogEventTypesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Request-Id

	xRequestID := o.XRequestID
	if xRequestID != "" {
		rw.Header().Set("X-Request-Id", xRequestID)
	}

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
