apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-harbor-image
spec:
  description: Harbor need to use the makefile to build image, it is not a normal build process. So we need to build the image in this pipeline.
  params:
    - name: reuse-artifact
      description: >-
        If set to true, the task will reuse the built image from the previous run.
        This is useful for speeding up the build process when the image has not changed.
      default: "true"

    - name: image-namespace
      description: Image repository address like build-harbor.alauda.cn/test
      type: string
      default: "build-harbor.alauda.cn/devops"

    - name: base-image-namespace
      description: Image repository address like build-harbor.alauda.cn/test. It is used to build the base image by Dockerfile.base.
      type: string
      default: "build-harbor.alauda.cn/devops"

    - name: component-name
      description: The name of the component to be built.
      type: string

    - name: image-tag
      description: The tag to be added to the built image.
      type: string

    - name: build-path
      description: Path to the directory to build the image from
      type: string
      default: "./subtree/harbor"

    - name: pre-build-command
      description: The command to be used to pre-build the image.
      type: string
      default: |
        # bind docker config
        if [ "$(workspaces.cache.bound)" == "true" ]; then
          export DOCKER_CONFIG="$(mktemp -d)"
          if [ -e "$HOME/.docker/buildx" ]; then
            ln -s ~/.docker/buildx $DOCKER_CONFIG/buildx
          fi
          # Supports two types of credentials: config.json and .dockerconfigjson
          echo "==> setting up docker config environment variable: ${DOCKER_CONFIG}/config.json"
          if [ -f "$(workspaces.cache.path)/config.json" ]; then
            cp "$(workspaces.cache.path)/config.json" ${DOCKER_CONFIG}/config.json
          elif [ -f "$(workspaces.cache.path)/.dockerconfigjson" ]; then
            cp "$(workspaces.cache.path)/.dockerconfigjson" ${DOCKER_CONFIG}/config.json
          fi
        fi
        
        # Check if we should try to reuse artifacts
        if [ "$(params.reuse-artifact)" == "true" ]; then
          image_url=$(params.image-namespace)/goharbor-harbor-$(params.component-name):$(params.image-tag)
          echo "==> Checking for existing artifacts..."
          digest=$(docker buildx imagetools inspect "${image_url}" | grep -i '^Digest:' | head -n1 | awk '{print $2}')
          if [ -n "${digest}" ]; then
            echo "==> ✅ Tag exists, skipping build..."
            exit 0
          else
            echo "==> Not all tags exist, proceeding with build..."
          fi
        fi
        
        apt-get update && apt-get install -y wget
        
        export IMAGENAMESPACE=$(params.image-namespace)
        export BASEIMAGENAMESPACE=$(params.base-image-namespace)
        export VERSIONTAG=$(params.image-tag)-$ARCH
        export BASEIMAGETAG=$(params.image-tag)-$ARCH
        export PUSHBASEIMAGE=false
        export DOCKERBUILD="docker buildx build --platform=linux/$ARCH --builder builder --push --metadata-file .build-metadata.txt"

    - name: build-command
      description: The command to be used to build the image.
      type: string

    - name: post-build-command
      description: The command to be used to post-build the image.
      type: string
      default: |
        echo "==== build metadata"
        cat .build-metadata.txt
        echo "==== build metadata"

  workspaces:
    - name: source-amd64
      description: Workspace for shared code source
    - name: source-arm64
      description: Workspace for shared code source
    - name: dockerconfig
      description: >-
        Workspace for Docker configuration files, such as `config.json` or `.dockerconfigjson`.
        This is optional and is used for authentication when pushing images to the registry.
      optional: true

  tasks:
    - name: build-amd64-image
      timeout: 60m
      retries: 3
      taskRef:
        resolver: hub
        params:
          - name: catalog
            value: alauda
          - name: type
            value: tekton
          - name: name
            value: docker-in-docker
          - name: version
            value: "0.2"
      workspaces:
        - name: source
          workspace: source-amd64
        - name: cache
          workspace: dockerconfig
      params:
        - name: tools-image
          value: registry.alauda.cn:60080/devops/alauda-docker-buildx:latest
        - name: command
          value: |
            set -ex
            
            ARCH=amd64
            
            echo "=> Running pre build command..."
            $(params.pre-build-command)
            
            echo "=> Building $ARCH image..."
            $(params.build-command)
            
            echo "=> Running post build command..."
            $(params.post-build-command)

    - name: build-arm64-image
      timeout: 60m
      retries: 3
      taskRef:
        resolver: hub
        params:
          - name: catalog
            value: alauda
          - name: type
            value: tekton
          - name: name
            value: docker-in-docker
          - name: version
            value: "0.2"
      workspaces:
        - name: source
          workspace: source-arm64
        - name: cache
          workspace: dockerconfig
      params:
        - name: tools-image
          value: registry.alauda.cn:60080/devops/alauda-docker-buildx:latest
        - name: command
          value: |
            set -ex
            
            ARCH=arm64
            
            echo "=> Running pre build command..."
            $(params.pre-build-command)
            
            echo "=> Building $ARCH image..."
            $(params.build-command)
            
            echo "=> Running post build command..."
            $(params.post-build-command)

    - name: merge-images
      runAfter:
        - build-amd64-image
        - build-arm64-image
      timeout: 60m
      retries: 3
      taskRef:
        resolver: hub
        params:
          - name: catalog
            value: alauda
          - name: type
            value: tekton
          - name: kind
            value: pipeline
          - name: name
            value: docker-in-docker
          - name: version
            value: "0.2"
      workspaces:
        - name: cache
          workspace: dockerconfig
      params:
        - name: tools-image
          value: registry.alauda.cn:60080/devops/alauda-docker-buildx:latest
        - name: command
          value: |
            set -ex
            
            # bind docker config
            if [ "$(workspaces.cache.bound)" == "true" ]; then
              export DOCKER_CONFIG="$(mktemp -d)"
              if [ -e "$HOME/.docker/buildx" ]; then
                ln -s ~/.docker/buildx $DOCKER_CONFIG/buildx
              fi
              # Supports two types of credentials: config.json and .dockerconfigjson
              echo "==> setting up docker config environment variable: ${DOCKER_CONFIG}/config.json"
              if [ -f "$(workspaces.cache.path)/config.json" ]; then
                cp "$(workspaces.cache.path)/config.json" ${DOCKER_CONFIG}/config.json
              elif [ -f "$(workspaces.cache.path)/.dockerconfigjson" ]; then
                cp "$(workspaces.cache.path)/.dockerconfigjson" ${DOCKER_CONFIG}/config.json
              fi
            fi
            
            image_url=$(params.image-namespace)/goharbor-harbor-$(params.component-name):$(params.image-tag)
            docker manifest create ${image_url} ${image_url}-amd64 ${image_url}-arm64
            docker manifest push ${image_url}

